export const randomTextSmall: string[] = [
  '.',
  '..',
  '...',
  '....',
  '.....',
  '......',
  '.......',
  '........',
  '.........',
  '..........',
  '...........',
  '............',
  '.............',
  '..............',
  '!',
  '!!',
  '!!!',
  '!!!!',
  '!!!!!',
  '!!!!!!',
  '!!!!!!!',
  '!!!!!!!!',
  '!!!!!!!!!',
  '!!!!!!!!!!',
  '!!!!!!!!!!!',
  '!!!!!!!!!!!!',
  '!!!!!!!!!!!!!',
  '!!!!!!!!!!!!!!',
  '!!!!!!!!!!!!!!!',
  '!!!!!!!!!!!!!!!!',
  ' ',
  '  ',
  '   ',
  '    ',
  '     ',
  '      ',
  '       ',
  '        ',
  '         ',
  '          ',
  '           ',
  '            ',
  '             ',
  '              ',
  '               ',
  '                ',
  '                 ',
  '                  ',
  '0',
  '01',
  '012',
  '0123',
  '01234',
  '012345',
  '0123456',
  '01234567',
  '012345678',
  '0123456789',
  '01234567890',
  '012345678901',
  '0123456789012',
  '01234567890123',
  '012345678901234',
  '0123456789012345',
  '01234567890123456',
  '012345678901234567',
  '0123456789012345678',
  '01234567890123456789',
  '9',
  '98',
  '987',
  '9876',
  '98765',
  '987654',
  '9876543',
  '98765432',
  '987654321',
  '9876543210',
  '98765432109',
  '987654321098',
  '9876543210987',
  '98765432109876',
  '987654321098765',
  '9876543210987654',
  '98765432109876543',
  '987654321098765432',
  '9876543210987654321',
  '98765432109876543210',
  'Of.',
  'Of any.',
  'Of anything.',
  'Of anything good.',
  'Of friendship.',
  'Of friendship on.',
  'Of friendship on inhabiting.',
  'Of friendship on inhabiting diminution.',
  'Of friendship on inhabiting diminution discovered.',
  'Of friendship on inhabiting diminution discovered as.',
  'Did friendly eat breeding building few nor.',
  'Object he barton no effect played valley afford.',
  'Period so to oppose we little seeing or branch.',
  'Announcing contrasted not imprudence add frequently you possession mrs.',
  'Period saw his houses square and misery.',
  'Hour had held lain give yet.',
  'Possession her thoroughly remarkably terminated man continuing.',
  'Removed greater to do ability.',
  'You shy shall while but wrote marry.',
  'Call why sake has sing pure.',
  'Gay six set polite nature worthy.',
  'So matter be me we wisdom should basket moment merely.',
  'Me burst ample wrong which would mr he could.',
  'Visit arise my point timed drawn no.',
  'Can friendly laughter goodness man him appetite carriage.',
  'Any widen see gay forth alone fruit bed.',
  'Not far stuff she think the jokes.',
  'Going as by do known noise he wrote round leave.',
  'Warmly put branch people narrow see.',
  'Winding its waiting yet parlors married own feeling.',
  'Marry fruit do spite jokes an times.',
  'Whether at it unknown warrant herself winding if.',
  'Him same none name sake had post love.',
  'An busy feel form hand am up help.',
  'Parties it brother amongst an fortune of.',
  'Twenty behind wicket why age now itself ten.',
  'Ham followed now ecstatic use speaking exercise may repeated.',
  'Himself he evident oh greatly my on inhabit general concern.',
  'It earnest amongst he showing females so improve in picture.',
  'Mrs can hundred its greater account.',
  'Distrusts daughters certainly suspected convinced our perpetual him yet.',
  'Words did noise taken right state are since.',
  'By impossible of in difficulty discovered celebrated ye.',
  'Justice joy manners boy met resolve produce.',
  'Bed head loud next plan rent had easy add him.',
  'As earnestly shameless elsewhere defective estimable fulfilled of.',
  'Esteem my advice it an excuse enable.',
  'Few household abilities believing determine zealously his repulsive.',
  'To open draw dear be by side like.',
  'Residence certainly elsewhere something she preferred cordially law.',
  'Age his surprise formerly mrs perceive few stanhill moderate.',
  'Of in power match on truth worse voice would.',
  'Large an it sense shall an match learn.',
  'By expect it result silent in formal of.',
  'Ask eat questions abilities described elsewhere assurance.',
  'Appetite in unlocked advanced breeding position concerns as.',
  'Cheerful get shutters yet for repeated screened.',
  'An no am cause hopes at three.',
  'Prevent behaved fertile he is mistake on.',
  'An country demesne message it.',
  'Bachelor domestic extended doubtful as concerns at.',
  'Morning prudent removal an letters by.',
  'On could my in order never it.',
  'Or excited certain sixteen it to parties colonel.',
  'Depending conveying direction has led immediate.',
  'Law gate her well bed life feet seen rent.',
  'On nature or no except it sussex.',
  'He share of first to worse.',
  'Weddings and any opinions suitable smallest nay.',
  'My he houses or months settle remove ladies appear.',
  'Engrossed suffering supposing he recommend do eagerness.',
  'Commanded no of depending extremity recommend attention tolerably.',
  'Bringing him smallest met few now returned surprise learning jennings.',
  'Objection delivered eagerness he exquisite at do in.',
  'Warmly up he nearer mr merely me.',
  'For though result and talent add are parish valley.',
  'Songs in oh other avoid it hours woman style.',
  'In myself family as if be agreed.',
  'Gay collected son him knowledge delivered put.',
  'Added would end ask sight and asked saw dried house.',
  'Property expenses yourself occasion endeavor two may judgment she.',
  'Me of soon rank be most head time tore.',
  'Colonel or passage to ability.',
  'Am increasing at contrasted in favourable he considered astonished.',
  'As if made held in an shot.',
  'By it enough to valley desire do.',
  'Mrs chief great maids these which are ham match she.',
  'Abode to tried do thing maids.',
  'Doubtful disposed returned rejoiced to dashwood is so up. Doubtful disposed returned rejoiced to dashwood is so up.',
  '把百度设为主页关于百度',
];

export const randomTextBig: string[] = randomTextSmall.concat([
  '把百度设为主页关于百度 把百度设为主页关于百度',
  '把百度设为主页关于百度 把百度设为主页关于百度 把百度设为主页关于百度',
  '把百度设为主页关于百度 把百度设为主页关于百度 把百度设为主页关于百度 把百度设为主页关于百度',
  '把百度设为主页关于百度 把百度设为主页关于百度 把百度设为主页关于百度 把百度设为主页关于百度 把百度设为主页关于百度',
]);
